image: ghcr.io/cpp-review-dune/introductory-review/hdnum

tasks:
  - name: Install JuliaLang
    command: |
      sudo pacman -Syyu julia ripgrep git --noconfirm --needed >/dev/null 2>&1
      julia -e 'using Pkg; Pkg.add("JuMP"); Pkg.add("GLPK")'
