image: registry.gitlab.com/dune-archiso/images/dune-archiso-yay

tasks:
  - name: Install JuliaLang
    command: |
      sudo pacman -Syyu julia ripgrep --noconfirm --needed >/dev/null 2>&1
      julia -e 'using Pkg; Pkg.add("JuMP"); Pkg.add("GLPK")'
