image: ghcr.io/cpp-review-dune/introductory-review/hdnum

tasks:
  - name: Install JuliaLang
    command: |
      sudo pacman -Syyu julia git --noconfirm --needed
      julia -e 'using Pkg; Pkg.add("JuMP"); Pkg.add("GLPK")'