image: ghcr.io/cpp-review-dune/introductory-review/hdnum

tasks:
  - name: Install JuliaLang
    command: |
      sudo -Syyu julia --noconfirm --needed
      julia -e 'import Pkg; Pkg.add("JuMP", "GLPK")'